### ISSUE TITLE
Why no new line at the end?

### ISSUE THREAD

**Issue by anastasia-stepanchenko** [QuantLet/QID-2086-MVAcancarm#1]
Why do you think, there must be no new line at the end of the file? It should have one if we don't wanna make an additional ENTER-click for execution of the last code line, while copy-pasting it into the R Console.

By the way, formatR creates it ...

**Comment by polarstern** [comment]
Because if you upload it to Quantnet, there will be this empty line like here http://quantnet.wiwi.hu-berlin.de/index.php?p=show&id=1196
And our style is like here http://quantnet.wiwi.hu-berlin.de/index.php?p=show&id=1213

**Comment by anastasia-stepanchenko** [comment]
Oh, then my R Console must be too capricious. Thanks for the answer.

**Comment by lborke** [comment]
I agree with Nastja.
In Windows it is a good idea to have a new line after a block of commands in R. Otherwise you have to enter "Enter" for execution.

It is ok to have an empty line in the beginning AND in the end of a Q.
I have now adjusted:
http://quantnet.wiwi.hu-berlin.de/index.php?p=show&id=1213

;-)))

**Comment by polarstern** [comment]
Ok :-)
